name: Plop
version: 1.0.0
main: com.brinkmc.plop.Plop
description: Plop, combining plots and shops
author: Noah Stone
website: https://brinkmc.com
api-version: '1.20'
depend: [Vault, WorldEdit, WorldGuard, Guilds, MythicMobs, packetevents]
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.20.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.20.0
  - com.zaxxer:HikariCP:6.2.1
  - net.kyori:adventure-text-minimessage:4.18.0
  - net.kyori:adventure-text-serializer-plain:4.18.0
  - net.kyori:adventure-text-serializer-legacy:4.18.0
  - net.kyori:adventure-platform-bukkit:4.3.4