name: Plop
version: 1.0.0
main: com.brinkmc.plop.Plop
description: Plop, combining plots and shops
author: Noah Stone
website: https://brinkmc.com
api-version: '1.20'
depend: [Vault, WorldEdit, WorldGuard, Guilds, MythicMobs, MythicCrucible]
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.20.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.20.0